version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    command: ["python", "-m", "backend.main"]
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app/backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: .
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: modelguard-network
